USE [master]
GO

CREATE DATABASE [a1caida]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'a1caida', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\a1caida.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'a1caida_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\a1caida_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [a1caida].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [a1caida] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [a1caida] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [a1caida] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [a1caida] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [a1caida] SET ARITHABORT OFF 
GO

ALTER DATABASE [a1caida] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [a1caida] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [a1caida] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [a1caida] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [a1caida] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [a1caida] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [a1caida] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [a1caida] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [a1caida] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [a1caida] SET  ENABLE_BROKER 
GO

ALTER DATABASE [a1caida] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [a1caida] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [a1caida] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [a1caida] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [a1caida] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [a1caida] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [a1caida] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [a1caida] SET RECOVERY FULL 
GO

ALTER DATABASE [a1caida] SET  MULTI_USER 
GO

ALTER DATABASE [a1caida] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [a1caida] SET DB_CHAINING OFF 
GO

ALTER DATABASE [a1caida] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [a1caida] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [a1caida] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [a1caida] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [a1caida] SET QUERY_STORE = OFF
GO

ALTER DATABASE [a1caida] SET  READ_WRITE 
GO

USE [a1caida]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[word_statistics](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[word] [varchar](50) NULL,
	[count] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[word_statistics] ADD  DEFAULT (NULL) FOR [word]
GO

ALTER TABLE [dbo].[word_statistics] ADD  DEFAULT (NULL) FOR [count]
GO

